# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'treatment_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_treatment_window(object):
    def setupUi(self, treatment_window):
        treatment_window.setObjectName("treatment_window")
        treatment_window.resize(287, 401)
        self.verticalLayoutWidget = QtWidgets.QWidget(treatment_window)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 10, 251, 371))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.comboBox = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout.addWidget(self.comboBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.textBrowser = QtWidgets.QTextBrowser(self.verticalLayoutWidget)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout.addWidget(self.textBrowser)
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.pushButton_6 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout.addWidget(self.pushButton_6)
        self.pushButton_3 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout.addWidget(self.pushButton_4)

        self.retranslateUi(treatment_window)
        QtCore.QMetaObject.connectSlotsByName(treatment_window)

    def retranslateUi(self, treatment_window):
        _translate = QtCore.QCoreApplication.translate
        treatment_window.setStyleSheet("background-color: rgb(200, 200, 255);")
        treatment_window.setWindowTitle(_translate("treatment_window", "Dialog"))
        self.label.setText(_translate("treatment_window", "Лечение"))
        self.label_2.setText(_translate("treatment_window", "Выберите лечение"))
        self.pushButton.setText(_translate("treatment_window", "Удалить"))
        self.pushButton_2.setText(_translate("treatment_window", "Добавить новое лечение"))
        self.pushButton_3.setText(_translate("treatment_window", "Приемы"))
        self.pushButton_4.setText(_translate("treatment_window", "Пациенты"))
        self.pushButton_6.setText(_translate("treatment_window", "Изменить"))
